version: "2"

services:
  rng:
    image: yfanha/dockercoins_rng
    ports:
    - "8001:80"

  hasher:
    image: yfanha/dockercoins_hasher
    ports:
    - "8002:80"

  webui:
    image: yfanha/dockercoins_webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis

  worker:
    image: yfanha/dockercoins_worker:0.1

